### ISSUE TITLE
The same grey colors

### ISSUE THREAD

**Issue by krnl0138** [RRethy/vim-hexokinase#10]
I installed plugin via Plug as usual, functions are working properly, but every time I see the same greyish color output, despite all changes in options it stays the same. 
No difference in vim and neovim.

What did I do wrong?

Neovim 0.3.4-2
gvim 8.1.0996-1
A messy vimrc file here: https://pastebin.com/U6CMfSST

**Comment by ferk6a** [comment]
This plugin works using `guifg`. If you're working on a terminal, you have to use [a terminal that supports true color](https://gist.github.com/XVilka/8346728) and you also need to set `termguicolors`.

I think the author could make this clearer in the documentation, but that's about it, I'm pretty happy with the results myself:
![image](https://user-images.githubusercontent.com/3057302/55005825-78762c80-4fbb-11e9-8118-09c1bb1b4709.png)

**Comment by RRethy** [comment]
@fer22f is correct, you need `:h termguicolors` to be on. My bad for not documenting anywhere, I'll add it to README and docs.

**Comment by RRethy** [comment]
Going to reopen this so that if anyone else has this issue they can see the comments.

**Comment by crivotz** [comment]
My two cents
I use vim inside tmux with base16 shell
Enabling `termguicolors` I lost all my colorscheme, to solve I had to add the following lines:

```
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
