### ISSUE TITLE
show first color of the line instead of last

### ISSUE THREAD

**Issue by habamax** [RRethy/vim-hexokinase#12]
Now if there are more than 1 colors on the line -- the last one is showed/highlighted with `sign_column`:

![image](https://user-images.githubusercontent.com/234774/55056468-432f1480-5077-11e9-9fe3-27ffca9ba048.png)

It is probably more logical/convenient to show the first color? I can't say for everybody though.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.

**Comment by Asheq** [comment]
@RRethy Could you make this configurable via a variable or something? For one particular file, I would like to see the last color. Thanks!

**Comment by RRethy** [comment]
Add `let g:Hexokinase_prioritizeHead=0` to show the last colour. Currently not tied to a filetype and not documented.

**Comment by RRethy** [comment]
Add `let b:Hexokinase_prioritizeHead = 0` into a ftplugin to make this setting specific to a filetype.
