### ISSUE TITLE
Errors when colorscheme is changed

### ISSUE THREAD

**Issue by habamax** [RRethy/vim-hexokinase#13]
If you have:

![image](https://user-images.githubusercontent.com/234774/55057178-7a062a00-5079-11e9-8d00-32e5affe6d58.png)

And then change colorscheme + `:HexokinaseRefresh`:

![image](https://user-images.githubusercontent.com/234774/55057216-9e620680-5079-11e9-9023-c74ca5a7dfde.png)

Then Toggle

![image](https://user-images.githubusercontent.com/234774/55057236-ac178c00-5079-11e9-806d-a04fe5665109.png)

And toggle again -- it works:

![image](https://user-images.githubusercontent.com/234774/55057248-b76ab780-5079-11e9-86cf-bcb7c9739ffa.png)

**Comment by RRethy** [comment]
Thanks for catching this. I was keeping a list of ids, but I was not removing deleted ids from that list, so if you toggle the highlighting on twice it would have ids leftover which caused matchdelete to fail.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
