### ISSUE TITLE
cannot use 'virtual'

### ISSUE THREAD

**Issue by prankousky** [RRethy/vim-hexokinase#14]
Hi,

I stumbled upon this plugin on reddit and had to check it out right away. This is in my `.vimrc`:

```
set tgc
let g:Hexokinase_highlighters = ['virtual']
let g:Hexokinase_virtualText= '_____' (actually blocks, not line)
let g:Hexokinase_ftAutoload = ['*']
let g:Hexokinase_refreshEvents = ['TextChanged', 'TextChangedI']
```

When I open a file containing color codes in vim, nothing happens. When I `:HexokinaseToggle`, I get 

```
Error executing "home/me/.config/nvim/plugged/vim-hexokinase/autoload/hexokinase/highlighters/virtual.vim":
Line 1:
E117: unknown function: nvim_create_namespace
Error executing "function hexokinase#toggle_scraping":
Line 4:
E171 missing :endif
```

When I use `sign_column` instead, it works.  However, I do not want the color all the way to the left when I could actually have them on the right next to the actual color values.

Also, is there a way to auto-enable the plugin? With the lines above in my config, I still have to manually toggle it to work.

Thanks in advance for your help.

**Comment by RRethy** [comment]
The requirements for virtual text in `vim-hexokinase` is Neovim 0.3.2. Make sure you are using at least that version of Neovim.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
