### ISSUE TITLE
Undefined variable: b:sign_ids

### ISSUE THREAD

**Issue by airblade** [RRethy/vim-hexokinase#15]
Hello!

I just installed the plugin (at df1f0f5a).  I added these lines to my vimrc:

```viml
let g:Hexokinase_ftAutoload = ['css', 'sass']
let g:Hexokinase_refreshEvents = ['CursorHold']
```

When I launch vim with a file, `$ vim app/frontend/styles/foo.sass`, I get this error message:

```
Error detected while processing function <SNR>50_on_refresh_event[2]..hexokinase#tear_down[2]..hexokinase#highlighters#sign_column#tearDown:
line 1:
E121: Undefined variable: b:sign_ids
```

I'm using Vim 8.1.822.

**Comment by airblade** [comment]
If Vim is already open and I edit a buffer, everything's fine.  For example:

```
$ vim
:edit app/frontend/styles/foo.sass
```

**Comment by antaed** [comment]
I have almost the same issue, except I can't make it work as described by airblade above.
Here's an output of the full error message:

`Error detected while processing function .hexokinase#toggle_scraping[4]..hexokinase#scrape_colours[46]..hexokinase#highlighters#sign_column#highlight:
line    5:
E239: Invalid sign text: <bf>`

I should mention the issue occurs in gVim 8.1.1 on my Windows machine, and everything works fine on MacVim with pretty much identical vimrc.

**Comment by RRethy** [comment]
@airblade I couldn't recreate the issue, however that commit should fix it. Can you try it and let me know if it persists. Also ensure that the intended behaviour occurs.

**Comment by RRethy** [comment]
I would also highly recommend not using `CursorHold` to trigger a refresh.

**Comment by airblade** [comment]
Works for me.  Thanks.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
