### ISSUE TITLE
Buffer variables

### ISSUE THREAD

**Issue by autrimpo** [RRethy/vim-hexokinase#17]
Would it be possible to add `b:` versions of the configuration variables that would have higher priority? I have a custom pattern configured that makes sense only for a particular filetype, so I'd prefer to not clutter the global pattern list with it.

**Comment by RRethy** [comment]
Pushed! Documentation can be found [here](https://github.com/RRethy/vim-hexokinase/commit/395381e78c1039d81b986823ff146159f10c6046).

**Comment by autrimpo** [comment]
This was fast! Thank you.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
