### ISSUE TITLE
I have almost the same issue, except I can't make it work as described by airblade above.

### ISSUE THREAD

**Issue by RRethy** [RRethy/vim-hexokinase#18]
I have almost the same issue, except I can't make it work as described by airblade above.
Here's an output of the full error message:

`Error detected while processing function .hexokinase#toggle_scraping[4]..hexokinase#scrape_colours[46]..hexokinase#highlighters#sign_column#highlight:
line    5:
E239: Invalid sign text: <bf>`

I should mention the issue occurs in gVim 8.1.1 on my Windows machine, and everything works fine on MacVim with pretty much identical vimrc.

_Originally posted by @antaed in https://github.com/RRethy/vim-hexokinase/issues/15#issuecomment-477754204_

**Comment by RRethy** [comment]
@antaed That seems to be a different issue so I opened a new issue. Can you provide the output of `echo g:Hexokinase_signIcon`. If I had to guess, you are most likely providing it an invalid value for the sign column, it must be a printable character and can only occupy one or two display cells.

**Comment by antaed** [comment]
thanks for the reply, the output is  `<bf>`
i changed to a letter and it does indeed work...

**Comment by antaed** [comment]
your fix worked for me, thanks 👍

**Comment by antaed** [comment]
I managed to solve the issue by adding this to my _gvimrc:
`scriptencoding utf-8`
