### ISSUE TITLE
Foreground / background highlighters only highlight the hash character

### ISSUE THREAD

**Issue by kirjavascript** [RRethy/vim-hexokinase#20]
![](https://i.imgur.com/ZzdtpSb.png)

is there a way to make it colour in the whole number instead?

**Comment by RRethy** [comment]
Yes, it would involve creating your own highlighter. `foreground` and `background` were mainly done just to show the extensibility of the plugin. I'd recommend reading `:h Hexokinase-highlighters` and [the current implementation of foreground highlighter](https://github.com/RRethy/vim-hexokinase/blob/master/autoload/hexokinase/highlighters/foreground.vim). If you do get a working version, you can submit a PR with the file in the same location as the other highlighters to add a new highlighter to vim-hexokinase. It should require only small modifications to the existing foreground highlighter, you may even be able to iron out a few bug that `foreground` currently has.

**Comment by RRethy** [comment]
You might also find [this](https://github.com/RRethy/vim-hexokinase/issues/16) useful to colour those variables.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file (foreground/background/foregroundfull/backgroundfull work more reliably now)!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
