### ISSUE TITLE
.Xresources incompatibilities

### ISSUE THREAD

**Issue by sidalit** [RRethy/vim-hexokinase#23]
Hi,

Thanks for this plugin, however it seems there are some incompatibilities with colors define in  `~/.Xresources`.

My setup:
- Tilix terminal
- neovim:
```
nvim --version
NVIM v0.4.0-620-geada8f5aa
```
- `termguicolors` is enabled

Describing the issue with screenshot is better in this case
![Screenshot-2019-04-29-08-10-21-492x589](https://user-images.githubusercontent.com/9877335/56906215-a20cf280-6a56-11e9-9a09-581257a27a7c.png)

The example `~.Xresources` has been taken from Nord repositories : https://github.com/arcticicestudio/nord-xresources/blob/develop/src/nord

Let me know if you need more informations.

**Comment by RRethy** [comment]
This is intended behaviour. At the start of the line, `#def` is getting picked up as a valid three digit colour hex, it has the full hex of `#ddeeff` which is the colour that is being shown.

You are able to disable patterns which may be something you want to try. Right now by default the patterns that get matched are full hex values, three digit hex values, rgb functions, rgba functions. You might want to add this to your `vimrc` or `init.vim` to not match three digit hex values.

```vim
let g:Hexokinase_optInPatterns = [
			\ 'full_hex',
			\ 'rgb',
			\ 'rgba'
			\ ]
```

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
