### ISSUE TITLE
Unable to autoload hightlighting

### ISSUE THREAD

**Issue by SethBarberee** [RRethy/vim-hexokinase#24]
Issue is similar to #19. I can confirm that changing the highlighters or icon works. However, I can only see the colors when I manually run `HexokinaseToggle`. 

I've tried autoloading only on lua and enabling it globally and both do not work.

**Comment by RRethy** [comment]
Can you update your [dotfiles](https://github.com/SethBarberee/dotfiles) so I can look through them. I was never able to reproduce #19 so I still suspected that it was a configuration issue.

**Comment by SethBarberee** [comment]
Doh, found I had a spelling error with the option and it works now.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
