### ISSUE TITLE
Multiple colors in the same line with 'virtual' highlighter

### ISSUE THREAD

**Issue by aymanbagabas** [RRethy/vim-hexokinase#29]
The `virtual` highlighter doesn't display multiple colors in the same line ex.
![image](https://user-images.githubusercontent.com/3187948/65290248-7d580b00-db1c-11e9-8f56-7a3483005e6a.png)
Shows yellow but no red.

Also, as you can see, `backgroundfull` gets set even though it's not in my `let g:Hexokinase_highlighters` array list?

**Comment by RRethy** [comment]
From `:h g:Hexokinase_highlighters`:

```
"virtual" will use Neovim's virtual text feature
(|nvim_buf_set_virtual_text()|) to display
the colour. However, only one colour per line can be
displayed.
```

Virtual text is only able to display a single colour per line.

As for the `backgroundfull` being set, I don't think it is set. I think that is from another plugin such as coc.nvim which has a highlighting feature. Do you by chance use coc.nvim?

**Comment by aymanbagabas** [comment]
> Virtual text is only able to display a single colour per line.

I see. Thank you for the clarification.

> As for the `backgroundfull` being set, I don't think it is set. I think that is from another plugin such as coc.nvim which has a highlighting feature. Do you by chance use coc.nvim?

Indeed I do and that's what caused the problem.
