### ISSUE TITLE
Error when saving any file or executing HexokinaseToggle

### ISSUE THREAD

**Issue by timonson** [RRethy/vim-hexokinase#30]
Error detected while processing function hexokinase#v2#scraper#toggle[5]..hexokinase#v2#scraper#on[1]..<SNR>215_cancel_cur_job:
line    3:
E117: Unknown function: chanclose
Error detected while processing function hexokinase#v2#scraper#toggle:
line    5:
E171: Missing :endif

I would be happy to give more information, if needed.

**Comment by RRethy** [comment]
I've been solely using Neovim, forgot to implement the job control side of things for Vim when I released v2 of the plugin which is why you are getting the E117. When I get a chance either today or tmrw I'll put up a fix mb.

**Comment by RRethy** [comment]
The newest commit should fix it. If you could try it out and let me know if you encounter any other errors. I don't really use Vim much and it has a very different async api than Neovim so it might have bugs I'm unaware of.
