### ISSUE TITLE
Make command seems to silently fail

### ISSUE THREAD

**Issue by amadeus** [RRethy/vim-hexokinase#33]
It appears the make command seems to silently fail for me? When I run it, it seems to run fine with no output, however also no folders seem to be created and I still have the log message when launching MacVim that says I need to upgrade.

Here's a [video](https://cdn.discordapp.com/attachments/365662117191352320/625873211623473162/broken.mp4) attempting to run make

**Comment by timonson** [comment]
Same here on Linux

**Comment by cheap-glitch** [comment]
Same here too on Arch Linux. I set up the `GOPATH` environment variable to point to a subdir in my home folder, and the executable is indeed created there, but I still get the upgrade message every time I launch gVim and the plugin doesn't work.

**Comment by RRethy** [comment]
I suspect it is due to the `$PATH` not having `$GOPATH/bin/` which is where the binary is put. Try upgrading and let me know if that fixes it. I changed where vim-hexokinase looks for the executable to `$GOPATH/bin/hexokinase`.

**Comment by cheap-glitch** [comment]
Yep, I deleted all the files, reinstalled it, and it works. Thank you!

**Comment by dominiklohmann** [comment]
This still silently fails if `$GOPATH` is unset.

**Edit:** More generally, it's pretty bad design when a vim plugin tries to install a dependency globally by itself. Please just install it to some subdirectory of `path/to/plugins/vim-hexokinase` if and only if no version of hexokinase is in `$PATH` and use it instead then.

**Comment by RRethy** [comment]
Can people try it out, I think I also fixed the issue in #31 which was due to me adding the submodule with `git@github.com:RRethy/hexokinase.git` instead of `https://github.com/RRethy/hexokinase.git`.

It no longer uses the global hexokinase by default.

**Comment by danbruegge** [comment]
Still getting the error.

**Comment by RRethy** [comment]
@danbruegge which error? The error from #31 or the message from `vim-hexokinase` telling you to upgrade?

Edit: NVM wasn't using location relative to the plugin root.

**Comment by danbruegge** [comment]
@RRethy - jep this one. But i manually set the `$GOPATH` and now it is gone.

**Comment by RRethy** [comment]
Going to leave this open for a bit. Kinda shit the bed on these hotfixes lol.

**Comment by danbruegge** [comment]
@RRethy - After your last change it works also without setting `$GOPATH`. :)

**Comment by RRethy** [comment]
Seems to be no more flare ups, closing issue.
