### ISSUE TITLE
Stuck processes?

### ISSUE THREAD

**Issue by amadeus** [RRethy/vim-hexokinase#36]
Just woke up my laptop from sleep this morning, and after a few minutes noticed the fans were going pretty hard. Checked the activity monitor and saw this:

<img width="440" alt="hexo" src="https://user-images.githubusercontent.com/83376/66509096-30b28080-ea87-11e9-9bd8-003dfa9e06f8.png">

Had to force quit all of them, to get them to stop.

**Comment by RRethy** [comment]
Tried reproducing but was unable.

Did you have Vim open when you put your laptop to sleep? Are you using Neovim or Vim? In your last Vim session, what type of files did you have open in terms of size, any of them in the 100s of mb? For the screenshot, do you have the `CPU time` column? Is this reoccurring or first time?

**Comment by RRethy** [comment]
@amadeus ^

**Comment by amadeus** [comment]
Sorry for the delays, been pretty busy lately. I haven't been able to figure out how to reliably repro the issue. It appears to just happen after normal usage, regardless of sleep. Opening a file manually, calling the toggle function, seems to have no effect.  

All I can really say, is after some time coding, I notice my CPU fans going, and when I check activity monitor, I see a bunch of stuck processes.

I've had to temporarily disable the plugin in the meantime.

**Comment by RRethy** [comment]
Neovim or Vim? And does it persist if you close (Neo)Vim? Having looked at your dotfiles, you are using an outdated option, `g:Hexokinase_ftAutoload` which was deprecated in favour of `g:Hexokinase_ftEnabled`. As a bandaid for now you could restrict the filetypes to `css`.

**Comment by amadeus** [comment]
Ok, so I think I figured out the cause of the issue.  I use this JSON files for color variable mappings - 

https://gist.github.com/amadeus/70d73e418e5c1014b101b38a9369d62f

It gets sourced like this:

```
let g:Hexokinase_palettes = [
  \ expand($HOME).'/.vim/bundle/vim-misc/misc/discord_colors.json',
\ ]
```

Simply opening this file, seems to just peg the hexo process, and it won't go away if I close the buffer, I have to shut down that vim instance completely.

**Comment by RRethy** [comment]
Should be fixed. Try updating and make sure `make hexokinase` gets executed since the bug was in the external scraper.

**Comment by amadeus** [comment]
Did a quick check at and it seems to be fixed! Thanks!

Will report back if I find any other stuck processes. 🥂
