### ISSUE TITLE
Support for ANSI escape sequences

### ISSUE THREAD

**Issue by nkakouros** [RRethy/vim-hexokinase#39]
[Here](https://github.com/niieani/bash-oo-framework/blob/master/lib/UI/Color.var.sh) is a list of colors in ANSI escape sequences format. Do you believe these could be also supported?

**Comment by RRethy** [comment]
Yea, you can add support with `g:Hexokinase_palettes`. When I get a chance I'll look into having [hexokinase](https://github.com/rrethy/hexokinase) scrape them.

**Comment by RRethy** [comment]
`:h g:Hexokinase_palettes` is the best bet here since each person would have a different colour shown based on their terminal colours. Closing since vim-hexokinase won't add this as a builtin.
