### ISSUE TITLE
Customize the size of the virtual square?

### ISSUE THREAD

**Issue by Asheq** [RRethy/vim-hexokinase#41]
I think it would be nice to be able to customize the size of the square, may be as a percentage of the line-height. The current square is a little small for my taste.

PS: This plugin is superb! Especially in conjunction with https://github.com/KabbAmine/vCoolor.vim

**Comment by RRethy** [comment]
`:h g:Hexokinase_virtualText` is what you want. Here are some possible values you might want to try.

```vim
let g:Hexokinase_virtualText = '█'
let g:Hexokinase_virtualText = '██'
let g:Hexokinase_virtualText = '███'
let g:Hexokinase_virtualText = '▀'
let g:Hexokinase_virtualText = '▄'
let g:Hexokinase_virtualText = '▓'
```

**Comment by Asheq** [comment]
@RRethy Ah yes, I missed that. Thanks!
