### ISSUE TITLE
[Windows incompatibility] Can't turn on highlighting after upgrading to v2

### ISSUE THREAD

**Issue by antaed** [RRethy/vim-hexokinase#43]
I can't turn on highlighting on Windows gVim after upgrading to v2. It won't autoload and I can't even turn it on with the HexokinaseToggle/HexokinaseTurnOn commands.
I tried reinstalling the plugin from scratch and I also tried to return to v1 with `let g:Hexokinase_v2 = 0`.
I have golang 1.12.9 installed and set to PATH.

**Comment by RRethy** [comment]
Can you try manually running `make hexokinase` in project root. It might be failing on windows, not sure too much about windows since I've only ever used OSX and Ubuntu. Also, when you return to v1, what happens, behaviour should remain, does it not?

**Comment by antaed** [comment]
I just manually ran `make hexokinase` in project root. The command didn't return any errors but I still don't get any highlighting.
Returning to v1 doesn't solve the issue, highlighting won't turn on, not even manually with the HexokinaseToggle/HexokinaseTurnOn commands.
I don't know if it has any relevance but I remind you about issue #19 which I reported some time ago and managed by adding `autocmd FileType css silent! HexokinaseToggle`  to my vimrc.

**Comment by RRethy** [comment]
I remember that issue, I still suspected there was an issue with the loading of the plugin since that autocmd should not have been needed in the first place and it hasn't been a reoccurring issue for others. Can you push your dotfiles to a repo so I can look at them.

**Comment by antaed** [comment]
Sure, here you can find my dotfiles on Windows:
[https://github.com/antaed/gvim_config](https://github.com/antaed/gvim_config)

**Comment by RRethy** [comment]
Make sure `let g:Hexokinase_v2 = 0` isn't left in your gvimrc. Try removing the autocmds as well, by default hexokinase v2 will turn on for all filetypes, so toggling it will then turn it off.

**Comment by antaed** [comment]
I already tried to solve the issue by removing those lines and did it again just now but it still doesn't work. To be clear, I tried all these combinations:
`let g:Hexokinase_v2 = 0` ON/OFF
`let g:Hexokinase_signIcon = '■'` ON/OFF
`autocmd FileType css silent! HexokinaseToggle` ON/OFF
I restarted vim after each try and, because the highlighting wasn't auto-enabled, I tried the manual commands as well.

**Comment by ghid** [comment]
I'm facing the same issue; I'm using Windows 10 too.

**Comment by RRethy** [comment]
Inside of the plugin root, try running `./hexokinase/hexokinase -files=test_colours.txt`. I don't have a windows machine so I can't test this.

**Comment by antaed** [comment]
When I run the command in gVim :terminal or in Command Prompt, I get a never-ending stream of words that is continuously drawn on the screen.
I tried to run the same command in PowerShell but weirdly I get this error: "the system cannot find file specified".

**Comment by RRethy** [comment]
Not sure much about differences with Windows so not sure how to fix. The Makefile probably needs to be updated to correctly build the program. If someone with a windows machine can get the `hexokinase` executable built, then I'll update the Makefile. If you get it built, you can also override `g:Hexokinase_executable_path` to use it.
