### ISSUE TITLE
Doesnt seem to show virtual mode or any mode.

### ISSUE THREAD

**Issue by thepenguinthatwants** [RRethy/vim-hexokinase#44]
I added this on my init.vim
```
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
let g:Hexokinase_highlighters = ['virtual']
```
![image](https://user-images.githubusercontent.com/46752217/68903033-8511e580-0742-11ea-8292-3e52d1ef062b.png)
And the demo file looks just like this.

**Comment by RRethy** [comment]
That looks like `let g:Hexokinase_highlighters = ['foreground']` is showing highlighting. Are you sure you aren't overriding this option elsewhere.

**Comment by thepenguinthatwants** [comment]
Hi you are right!

Somehow I had it before.. sorry and thank you
