### ISSUE TITLE
Highlighting collides with coc-css lsp

### ISSUE THREAD

**Issue by willdavidow** [RRethy/vim-hexokinase#48]
After installing `vim-hexokinase` I realized that the `coc-css` language server (using `coc-vim` for lsp support) is overriding highlighting provided by this plugin.

Other than removing the `coc-css` language server, it doesn't appear as though there's a way to have `vim-hexokinase` take precedence. I'm not sure if this issue is something that can be fixed here, or needs to be handled by configuring some options in `coc-css` (if those options exist), but figured this would be a good place to start - and maybe something already exists to fix this that I'm not aware of yet?

**Comment by RRethy** [comment]
`vim-hexokinase` cannot do anything about this you'll have to disable coc from highlighting. Try adding this to you `coc-settings.json`.

```json
"coc.preferences.colorSupport": false,
```

I'm not a coc user so I'm just going off what was posted in [another issue](https://github.com/RRethy/vim-hexokinase/issues/19#issuecomment-478284745).

**Comment by willdavidow** [comment]
Awesome - that did the trick! I guess I didn't look for a global option to do that, I was only looking at the ones for the specific language server and didn't see anything that would do it.. Thanks!
