### ISSUE TITLE
Possible to Add Variable Highlighting?

### ISSUE THREAD

**Issue by willdavidow** [RRethy/vim-hexokinase#49]
Wondering about a possible enhancement that would highlight colors referenced using variables. For example in SCSS:

```scss
$veryBlue: #0000FF; // this gets highlighted by Hexokinase

.someClass {
  background-color: $veryBlue; // but is it possible to highlight the variable usage here?
```

**Comment by RRethy** [comment]
You highlight arbitrary text using `:h g:Hexokinase_palettes`. So you could create a palette file with the variable names and the corresponding hex values.

However, highlighting variables truly intelligently wouldn't be possible with the current state of [hexokinase](github.com/rrethy/hexokinase) and would require a pretty sizeable PR to implement. https://github.com/norcalli/nvim-colorizer.lua has an open PR to do something similar, however, that plugin is lacking in many other areas. You might want to check it out to see if it better fights your use case.
