### ISSUE TITLE
List 0.3.2 as minimum nvim version

### ISSUE THREAD

**Issue by tom-james-watson** [RRethy/vim-hexokinase#5]
I installed the plugin with Plug and nothing happens when I open a file with listed colours. Manually running `HexokinaseRefresh` throws the following error:

```
Error detected while processing /home/tomw/.vim/plugged/vim-hexokinase/autoload/hexokinase/highlighters/virtual.vim:
line    1:
E117: Unknown function: nvim_create_namespace
E15: Invalid expression: nvim_create_namespace('')
Error detected while processing function hexokinase#tear_down[2]..hexokinase#highlighters#virtual#tearDown:
line    2:
E121: Undefined variable: s:namespace
E116: Invalid arguments for function nvim_buf_clear_namespace
```

**Comment by joereynolds** [comment]
Likely because it relies on Neovim's virtual text to be present, this was introduced in 0.3.2

**Comment by RRethy** [comment]
Adding this to README thanks.

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
