### ISSUE TITLE
Support for zero x hexadecimal notation as used in alacritty

### ISSUE THREAD

**Issue by wimstefan** [RRethy/vim-hexokinase#50]
First of all thank you for your hard work!

I've stumbled over this plugin and like it very much but there is one little thing missing: support for the zero x notation of colour names as it is used in [Alacritty config file](https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L186-L248).

Using g:Hexokinase_palettes seems quite tedious in this case if I understood the concept correctly?

**Comment by RRethy** [comment]
It would require adding a scraper to https://github.com/rrethy/hexokinase, updating the submodule inside vim-hexokinase, and adding documentation for his pattern. I'll write it when I get a chance, prob 1-2 weeks.

**Comment by RRethy** [comment]
Update the plugin and make sure to run `make hexokinase`.

**Comment by wimstefan** [comment]
Wow that was really fast!!!
Thank you so much Sir 🙏🏼
