### ISSUE TITLE
virtual mode not possible with more than one color in same line

### ISSUE THREAD

**Issue by joe23rep** [RRethy/vim-hexokinase#51]
idk why but on my maschine (arch, kde, neovim 0.4.3) virtual only shows the color of the first color in that line at the end of the line instead of showing every color directly after the colorcode.

signcolumn also only shows one color in a line and not multiple like in the screenshot. 

go is installed, and i did run make in the rootfolder of the plugin. maybe i did something wrong but this way its sadly not really usable. idk where the error lays cuz foreground and background (+full versions) work like they should. they display all colors correctly didrectly on the color code and not at the end of the line and only for one color (the first).

**Comment by RRethy** [comment]
Virtual will only ever show the first colour since virtual text only allows a single highlight group.

As for sign column only showing a single colour, what's the output of `:set signcolumn?`. You need it to match `(auto|yes):[2-9]`.

**Comment by RRethy** [comment]
Having looked at your dotfiles, you don't have multiple sign columns enabled, try adding `set signcolumn=auto:3` (replace 3 with [2-9]) to your init.vim.

**Comment by joe23rep** [comment]
is there the possibility that ull be able to achive a visual studio code like implementation of the virtual feature (showing it directly after the color code no matter how many color codes are in one line)? right now ill run it like i ran it with colorizer but the virtual style would be really nice (looks way nicer if u ask me)

**Comment by RRethy** [comment]
Neither Neovim nor Vim (nor any Neovim gui) have this capability.

You can try implementing it yourself if you know of a way to implement it that I don't with `:h hexokinase-custom-highlighters`, vim-hexokinase let's the user define custom highlight scripts.

Another option would be to use `let g:Hexokinase_highlighters = ['foreground']` which will only highlight specific parts of the match (only the `#` in `#ff00ff`).

**Comment by RRethy** [comment]
47e2063d481d6967f2b4c5d8942f38d3d1fb1005 now supports multiple colours in virtual text.
