### ISSUE TITLE
refreshEvents - 'TextChanged' and 'InsertLeave' not working and completely turn off highlighting

### ISSUE THREAD

**Issue by ghost** [RRethy/vim-hexokinase#53]
from `:h g:Hexokinase_refreshEvents`:

```
Refresh Events                                    g:Hexokinase_refreshEvents

                Type: |List| of |String|s
                Which |autocmd-events| trigger a refresh of highlighting.

                Default value: >
                let g:Hexokinase_refreshEvents = ['BufWrite', 'BufCreate']

                Since the scraping is done asynchronously and no more than a
                single scraping job is started per buffer, you can use more
                aggressive |autocmd-events|. For live updating you could use
                ['TextChanged', 'InsertLeave'].

```

My `init.vim`:

```
let g:Hexokinase_highlighters = [ 'backgroundfull' ]

let g:Hexokinase_optInPatterns = [
\     'full_hex',
\     'triple_hex',
\     'rgb',
\     'rgba',
\     'hsl',
\     'hsla',
\     'colour_names'
\ ]

let g:Hexokinase_refreshEvents = ['BufWrite', 'BufCreate', 'TextChanged', 'InsertLeave']
```

With the last line (`let g:Hexokinase_refreshEvents`), not only `TextChanged` or `InsertLeave` don't work, but color highlighting is completely disabled. I have to manually set it with either `:Hexokinase_Toogle` or `Hexokinase_TurnOn`

**Comment by RRethy** [comment]
Try changing it to

```vim
let g:Hexokinase_refreshEvents = ['BufWrite', 'BufRead', 'TextChanged', 'InsertLeave']
```

**Comment by RRethy** [comment]
The doc had an error fixed in #52, BufRead is used instead of BufCreate because BufCreate occurs too early.

**Comment by ghost** [comment]
> Try changing it to
> 
> ```viml
> let g:Hexokinase_refreshEvents = ['BufWrite', 'BufRead', 'TextChanged', 'InsertLeave']
> ```

Thanks! syntax highlighting is no longer disabled and `InsertLeave` works but `TextChanged` doesn't seem to, unless I misunderstand how it's supposed to work.

Let's say I have `#f1fa8c` in a file. I enter Insert mode and replace it with `#ff5555`, the color doesn't change until I exit Insert mode. To my understanding, the color highlighting should change as I replace `#f1fa8c` with `#ff5555` without having to exit Insert mode. Am I correct?

**Comment by RRethy** [comment]
That is not correct, you want `TextChangedI` as `TextChanged` will only be for text changes while you are not in insert mode.
