### ISSUE TITLE
cterm support

### ISSUE THREAD

**Issue by Gavinok** [RRethy/vim-hexokinase#55]
Would be nice to have cterm color support added. This way when people want to fiddle with their Vim color schemes they can also adapt their terminal colors.

**Comment by RRethy** [comment]
What's the difference between cterm colors and the web colours that are supported?

**Comment by RRethy** [comment]
I'm assuming you mean `:h cterm-colors`, in which case you have the ability to get your desired behaviour quite easily with `:h g:Hexokinase_palettes`. That being said, since cterm-colors overlap with web colours, this is not something that I would be able to add natively.
