### ISSUE TITLE
how to install with no plugin manager?

### ISSUE THREAD

**Issue by r3k2** [RRethy/vim-hexokinase#56]
Since I started to use vim 8.x I decided to never use plugin managers and use the new native manager build into VIM.

**Comment by RRethy** [comment]
The same way any other plugin would be installed using native packages feature. See `:h packages`.

I'd recommend using a plugin manager especially if you are new to Vim or new to the packages feature in Vim, minpac is a good wrapper around the packages feature.

Using the packages feature is very manual and tedious, you'll need to setup the `:h 'packpath'` option and then clone the repo into the start directory of your package. There are more in-depth guides available online for the packages feature. On top of that, you'll need to run `make hexokinase` in the root of the plugin.
