### ISSUE TITLE
Highlight does not move when add or delete line

### ISSUE THREAD

**Issue by paraduxos** [RRethy/vim-hexokinase#58]
Before (works great)
![2020-04-09_14-04](https://user-images.githubusercontent.com/62638818/78867747-d01ef300-7a6b-11ea-9345-11d1ba89bf60.png)

After deleting 1 line
![2020-04-09_14-04_1](https://user-images.githubusercontent.com/62638818/78867713-baa9c900-7a6b-11ea-98af-db5935e597b6.png)

This also happen with adding line

my `init.vim`
```
let g:Hexokinase_highlighters = ['backgroundfull']

" Add triple_hex
let g:Hexokinase_optInPatterns = ['full_hex,rgb,rgba,hsl,hsla,colour_names,triple_hex']
```

Additional information
```shell
$ nvim --version
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3

# inside nvim
:echo Hexokinase_v2
# Return 1
```

**Comment by RRethy** [comment]
Update Nvim to v0.4 and update this plugin and it should follow the word now.

**Comment by RRethy** [comment]
For reference, I updated the 'background' and 'backgroundfull' highlighters (the two foreground highlighters already used it, I just forgot to migrate the others) to use `nvim_buf_add_highlight` instead of `matchaddpos`.
