### ISSUE TITLE
doesn't detect color

### ISSUE THREAD

**Issue by eoli3n** [RRethy/vim-hexokinase#59]
![2020-05-08T11:07:44,421983441+02:00](https://user-images.githubusercontent.com/14223657/81390707-37d46680-911c-11ea-9dc6-dc42e727ca20.png)

https://github.com/eoli3n/dotfiles/blob/master/roles/neovim/files/init.vim

any idea ?

**Comment by RRethy** [comment]
Do you have `:h 'termguicolors'` turned on? Try `:set termguicolors`.

**Comment by eoli3n** [comment]
Worked ! Thx
