### ISSUE TITLE
Disable highlight in a terminal.

### ISSUE THREAD

**Issue by kevinhwang91** [RRethy/vim-hexokinase#60]
I'm very annoyed that hexokinase highlight in a terminal. Please disable it by default or make an option.

I'm using the hard code config of `g:Hexokinase_ftDisabled`, I don't think it's a good idea for terminals with different filetype.

**Comment by RRethy** [comment]
Terminals will only have one filetype which is the empty type. What is your value for `g:Hexokinase_ftDisabled`?

**Comment by kevinhwang91** [comment]
`let g:Hexokinase_ftDisabled = ['rnvimr', 'fzf']`, filetype will be specified by plugs when it creat the terminal window. The plugs using the terminal will be more and more.

**Comment by RRethy** [comment]
Hmm personally this seems fine to me, that's the purpose of having `let g:Hexokinase_ftDisabled`.  That being said, an argument could be made for `let g:Hexokinase_btDisabled` to be added which wouldn't be too hard to do. I'll make this as an enhancement, if you want to implement it wouldn't be too hard (just follow what is done for `g:Hexokinase_ftDisabled` and `g:Hexokinase_ftEnabled`). If not, I'll get to it when I have the time.

**Comment by RRethy** [comment]
#62
