### ISSUE TITLE
Disable alpha?

### ISSUE THREAD

**Issue by tamis-laan** [RRethy/vim-hexokinase#61]
When using rgba with a high amount of alpha the color is not readable enough. I would like to disable alpha preview, is this possible?

**Comment by RRethy** [comment]
There is the option `g:Hexokinase_alpha_bg` which will change the background colour used when calculating that alpha to make it more readable. By default it will use the background of your file (hl-Normal bg), but you could try `let g:Hexokinase_alpha_bg='#ffffff'` or `let g:Hexokinase_alpha_bg='#000000'` or even `:let g:Hexokinase_alpha_bg=synIDattr(hlID('Normal'), 'fg')`. That being said, the alpha cannot be disabled unfortunately.
