### ISSUE TITLE
nvim_buf_get_virtual_text only present in neovim v0.5

### ISSUE THREAD

**Issue by monkoose** [RRethy/vim-hexokinase#64]
After update, default settings for neovim  cause errors of missing `nvim_buf_get_virtual_text` function for release version of neovim.

**Comment by tuncenator** [comment]
I too am getting the same error on a fresh installation attempt:

![image](https://user-images.githubusercontent.com/21978273/86246188-4470ba80-bbb3-11ea-91d6-838cdbc707dd.png)

**Comment by RRethy** [comment]
574c8cf reverted 47e2063d481d6967f2b4c5d8942f38d3d1fb1005 to fix. I'll add this back with compatibility checks, I build from source so this function probably hasn't been released yet mb.
