### ISSUE TITLE
Missing pattern #rrggbbaa

### ISSUE THREAD

**Issue by lucas-miranda** [RRethy/vim-hexokinase#66]
Is it planned to support pattern **#rrggbbaa**?

Currently I'm using this config to partially colorize it:
`let g:Hexokinase_checkBoundary = 0`

But it feels a little hacky...

![a](https://user-images.githubusercontent.com/4644436/90980866-42ccce80-e534-11ea-82c5-527963553b95.png)

**Comment by RRethy** [comment]
I'm putting this in for now, I rushed the code so hopefully I didn't break anything. If I see a problem arise, I'll rollback and reimplement when I have more time to ensure no bugs.

**Comment by RRethy** [comment]
Also I have no plans no add 4 digit hex codes.
