### ISSUE TITLE
Multiple virtual text displays

### ISSUE THREAD

**Issue by mcauley-penney** [RRethy/vim-hexokinase#72]
Hey!

Firstly, thank you for hexokinase! I really enjoy this plugin

My question is less an issue and more a request for elaboration of documentation and features. I've read the documentation and it does not appear to have any information on whether multiple colors can be displayed at the end of the line using virtual text in neovim. I'd prefer this over using the sign column but am happily using the sign column to display multiple atm. Is it possible? 

Thank you for your time!

**Comment by RRethy** [comment]
It should show multiple colours in the virtual text, does it not show up for you?

**Comment by RRethy** [comment]
![image](https://user-images.githubusercontent.com/21000943/104855507-34b08d80-58db-11eb-87cf-029e5efc316a.png)
This is what I have.

**Comment by mcauley-penney** [comment]
Mine come out like this with virtual text. This is a total noob issue, I sincerely apologize haha

![hexokinase](https://user-images.githubusercontent.com/59481467/104860506-3719e400-58e9-11eb-9bfc-07698e668459.png)

**Comment by RRethy** [comment]
That's weird, can you try running `:echo exists('*nvim_buf_get_extmarks')` and post the output.

**Comment by mcauley-penney** [comment]
The output was simply 0. Im looking around for documentation on extmarks now

**Comment by RRethy** [comment]
In that case you are using v0.4.4 Neovim, you would have to upgrade your Neovim to I think v0.5 (nightly) to have multiple colours in the virtual text.

**Comment by mcauley-penney** [comment]
Thank you very much and I apologize again for the simple issue!

**Comment by RRethy** [comment]
Nw I didn't know that wasn't available on v0.4.4 either :)
