### ISSUE TITLE
Doesn't seem to refresh in insert mode

### ISSUE THREAD

**Issue by sTiKyt** [RRethy/vim-hexokinase#74]
Color will get updated only after i leave -- INSERT -- mode, i'd like it to update real-time like it is shown in README.md gifs
![image](https://user-images.githubusercontent.com/35602029/107992108-e53fa900-6fcf-11eb-9c84-8dfbce1d5fd4.png)
![image](https://user-images.githubusercontent.com/35602029/107992124-eb358a00-6fcf-11eb-9ad7-209fd0605c75.png)
![image](https://user-images.githubusercontent.com/35602029/107992133-f12b6b00-6fcf-11eb-91a3-df98280e1266.png)
![image](https://user-images.githubusercontent.com/35602029/107992136-f5578880-6fcf-11eb-8fc7-5c1073f15470.png)

**Comment by RRethy** [comment]
From the README:

```markdown
Note: By default all filetypes are scraped and highlighted on ['TextChanged', 'InsertLeave', 'BufRead'], see :h g:Hexokinase_refreshEvents for more info.
```

From the docs:

```
Refresh Events                                    *g:Hexokinase_refreshEvents*

                Type: |List| of |String|s
                Which |autocmd-events| trigger a refresh of highlighting.

                Default value: >
                let g:Hexokinase_refreshEvents = ['TextChanged', 'InsertLeave', 'BufRead']
```

The autocmd for text changing while in insert mode is `TextChangedI`.
