### ISSUE TITLE
no color highlighting

### ISSUE THREAD

**Issue by stevensonmt** [RRethy/vim-hexokinase#75]
I've cloned the repo to `.vim/git-plugins` and in the plugin directory run `make hexokinase`. The output of the make command is simply `git submodule init && git submodule update && cd hexokinase/ && go build`. In my vimrc I've got 
```
call plug#begin('~/.vim/git-plugins')
...
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
...
call plug#end()
```
I have `termguicolors` set.
I open a file with color codes in it and nothing happens. `:HexokinaseToggle` does nothing. What am I doing wrong?

**Comment by RRethy** [comment]
Hmm, that should work. What is the output of each of the following:

```vim
echo executable(g:Hexokinase_executable_path)
echo g:Hexokinase_ftDisabled
echo g:Hexokinase_ftEnabled
echo g:Hexokinase_highlighters
echo g:Hexokinase_optInPatterns
echo g:Hexokinase_refreshEvents
```

**Comment by stevensonmt** [comment]
> ```viml
> echo executable(g:Hexokinase_executable_path)
`1`
> ```viml
> echo g:Hexokinase_ftDisabled
`[]`
> ```viml
> echo g:Hexokinase_ftEnabled
`E121: Undefined variable: g:Hexokinase_ftEnabled`
> ```viml
> echo g:Hexokinase_highlighters
`['sign_column']`
> ```viml
> echo g:Hexokinase_optInPatterns
`full_hex,rgb,rgba,hsl,hsla,colour_names`
> ```viml
> echo g:Hexokinase_refreshEvents
`['TextChanged', 'InsertLeave', 'BufRead']`

**Comment by RRethy** [comment]
Maybe you have sign column disabled? Try `set signcolumn?`. Alternatively you can use a different method for highlighting (`:h g:Hexokinase_highlighters`).

**Comment by stevensonmt** [comment]
Brilliant. `signcolumn` was disabled. Changed highlighting method to foregroundfull and it's fantastic. Thanks!
