### ISSUE TITLE
Inaccurate colors with background highlighting method

### ISSUE THREAD

**Issue by stevensonmt** [RRethy/vim-hexokinase#76]
![Screenshot_2021-02-24_18-30-53](https://user-images.githubusercontent.com/8891908/109093716-ac898900-76cd-11eb-8cd7-1b63764bdfd9.png)
The screenshot above shows accurate colors in the signcolumn but inaccurate colors in the background highlights. I noticed similar behavior with the ap/vim-css-color plugin, though not identical. See: https://github.com/ap/vim-css-color/issues/147#issue-815119755

Any suggestions for troubleshooting this?

**Comment by RRethy** [comment]
Weird, maybe `:h 'termguicolors'` is off?

**Comment by stevensonmt** [comment]
I don't think so. `:set termguicolors?` returns `termguicolors` and `:set termguicolors` does not change anything.

**Comment by RRethy** [comment]
Can you post a minimal .vimrc/init.vim?

**Comment by stevensonmt** [comment]
```vim
set encoding=utf-8
set laststatus=2
set ch=1
set exrc
set shell=/bin/zsh
set number
set cursorline

" Open netrw Explore current dir if no file supplied on open
augroup ProjectDrawer
    autocmd!
    autocmd VimEnter * if argc() == 0 | Explore! | endif
augroup END


" Open files at last position or move to closest valid position
autocmd BufReadPost *
	\ if line("'\"") > 0 && line("'\"") <= line("$") |
	\   exe "normal g`\"" |
	\ endif
 
augroup END

" Tab settings
set tabstop=4
set shiftwidth=4 "autoindent is 4 spaces with <<
set expandtab "TAB converted to spaces

" Show invisible characters
set list
" Indicator characters for invisible characters
""" Note:  This may not show if you are not using a UTF-8 compatible
"""        terminal/editor
set listchars=tab:▸\ ,trail:•,extends:❯,precedes:❮
set showbreak=\

"" Searching
set hlsearch   " highlight matches
set incsearch  " incremental searching
set ignorecase " searches are case insensitive...
set smartcase  " If you use case then use case

" Instead of deleting what is being replaced, show a dollar sign
set cpoptions=ces$
" Turn on that syntax highlighting
syntax on

" Don't update the display while executing macros
set lazyredraw

" Indicate current mode
set showmode

" Enable enhanced command line completion.
set wildmenu
set wildmode=list:full

" Check if plug.vim installed and if not install it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let g:polyglot_disabled = ['rust', 'elm', 'elixir' ]

" load plugins
call plug#begin('~/.vim/git-plugins')
Plug 'dense-analysis/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
Plug 'andys8/vim-elm-syntax', { 'for': ['elm'] }
Plug 'junegunn/fzf.vim'
Plug 'itchyny/lightline.vim'
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'Raimondi/delimitMate'
Plug 'elixir-editors/vim-elixir'
Plug 'mhinz/vim-mix-format'

" Initialize plugin system
call plug#end()

set background=dark
 " Set color scheme
colorscheme bruvbox

let g:Hexokinase_highlighters=['backgroundfull']

" check terminal color compatibility
if has('nvim') || has('termguicolors')
	set termguicolors
	hi NonText ctermbg=none
	hi Normal guibg=NONE ctermbg=NONE
endif

" if hidden is not set, TextEdit might fail.
set hidden


 " Enable syntax highlighting
 syntax on

 " Enables filetype detection, loads ftplugin, and loads indent
 " (Not necessary on nvim and may not be necessary on vim 8.2+)
 filetype plugin indent on
```
I've left out stuff related to coc.nvim and ALE configuration but I don't think that's likely contributing.

**Comment by stevensonmt** [comment]
```vim
v2hexokinaseHighlight_withfg665c54▸ v2hexokinaseHighlight_withfg665c54
```
I ran `:so $VIMRUNTIME/syntax/hitest.vim` and all of the output showed the expected colors except for the v2hexokinaseHighlight entries. The above entry had the same greenish color as in the original screenshot, though it was not the only incorrect color -- just the one illegible due to FG and BG being the same.

**Comment by RRethy** [comment]
That .vimrc isn't *minimal*. Start with `vim --clean` and only load `vim-hexokinase`, then add your configuration for the plugin. I can't reproduce with the relevant parts of your vimrc so I can't fix the issue. Also include minimal text that it doesn't work on (like a file with one line that just has a hex code on it).

> I ran :so $VIMRUNTIME/syntax/hitest.vim and all of the output showed the expected colors except for the v2hexokinaseHighlight entries. The above entry had the same greenish color as in the original screenshot, though it was not the only incorrect color -- just the one illegible due to FG and BG being the same.

I don't really know what you mean, maybe include screenshots.

**Comment by stevensonmt** [comment]
Sorry. This is the minimal vimrc that recreates the issue for me:
```vim
" load plugins
call plug#begin('~/.vim/git-plugins')

Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
" Initialize plugin system
call plug#end()
let g:Hexokinase_highlighters=['backgroundfull']
set termguicolors


let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"
```
As for the minimal text, a text file with only `#665c54` demonstrates the issue.

**Comment by RRethy** [comment]
Change

```vim
let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"
```

to 

```vim
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

You terminal (and many others) don't support colons for separators. That being said, it's pretty rare that people need to set these options manually and your use seems to be the Vim default anyways so it can probably be removed without side affects (but I'm not confident).

**Comment by stevensonmt** [comment]
I did experiment without that setting and without it termguicolors has no effect. I'll try changing the colon to semicolon tonight. Thanks for looking into this.

**Comment by RRethy** [comment]
Sounds good, reopen if it doesn't resolve the issue.
