### ISSUE TITLE
Applies background full highlighter even though not enabled (NeoVim 0.4.4)

### ISSUE THREAD

**Issue by paulvt** [RRethy/vim-hexokinase#78]
When I open `test_colors.txt` in NeoVim, I initially see the squares and everything looks fine, but then within a second the background full highlighting is applied as well even though this is not configured.

(Hopefull) relevant parts of `init.vim`:
```vim
set termguicolors
set background=dark
" ...

Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
" ...

" Just to be sure, but works the same without
let g:Hexokinase_highlighters = [ 'virtual' ]
```

**Comment by paulvt** [comment]
I additionally noticed that if I configure:

```vim
let g:Hexokinase_optInPatterns = 'full_hex,rgb,rgba,hsl,hsla'
```

The line "green red blue" in `test_colours.txt` does not get a virtual text sign annotation, but it does also apply the background full highlighting to it later. So it seems that an additional run is done without looking at the config somehow?

**Comment by RRethy** [comment]
It sounds like you have another plugin providing colouring, can you try with `nvim --clean` and only load vim-hexokinase.

Also, can you paste the output of `echo g:Hexokinase_highlighters` and `echo g:Hexokinase_optInPatterns`?

**Comment by paulvt** [comment]
Another plugin? Might be. But if I disable `Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }`, there is no coloring whatsoever.

How to manually load the plugin? Using the `Plug` command does not seem to work?

Requested output (it's the defaults):

```vim
echo g:Hexokinase_highlighters
['virtual']
```
```vim
echo g:Hexokinase_optInPatterns
full_hex,rgb,rgba,hsl,hsla,colour_names
```

**Comment by paulvt** [comment]
Ok, I just commented out all plugins except hexikinase and then it works fine. So some other plugin triggers this, hmm. I will go through them and report back.

**Comment by paulvt** [comment]
That took way less longer than I thought. It is [coc.nvim](https://github.com/neoclide/coc.nvim) that once loaded interferes with vim-hexokinase. It was my first suspect as I assume it quite heavily dives into NeoVim. The use case for using both coc.nvim and vim-hexokinase in case of web programming is definitely there though 😅.

**Comment by RRethy** [comment]
I know there's a setting in coc to disable highlighting, I don't use coc though so I'm not sure what it is.

**Comment by RRethy** [comment]
Also `green red blue` get highlighted because the `g:Hexokinase_optInPatterns` includes `colour_names`.

**Comment by RRethy** [comment]
I think `"coc.preferences.colorSupport": false,` in your coc settings should work.

**Comment by paulvt** [comment]
As an extra note: I use the coc-highlighting plugin for symbol highlighting and I was never aware of its color highlighting support because I had `termguicolors` not turned on so it didn't work. I turned it on for `hexokinase` and so both implementations started to highlight.

Thanks for the quick reply! I like those virtual text indicators. I hope one day virtual text can also be inserted in a line so it can follow the color, but this is great for now!
