### ISSUE TITLE
Windows & Neovim not work but Gvim work fine

### ISSUE THREAD

**Issue by sphynx79** [RRethy/vim-hexokinase#79]
Hello, thnks for your plugin, but in Gvim work perfect, but in Neovim it dont's see the color.

This is version of my Neovim

```
NVIM v0.5.0-dev+1161-gfa4ee00fa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilato da runneradmin@fv-az152-366

Features: -acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM\sysinit.vim"
         $VIM di riserva: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by RRethy** [comment]
Can you post a minimal vimrc and example text file.

Make sure you have on `'termguicolors'`, you have Golang installed, the path found at `echo g:Hexokinase_executable_path` is executable.

**Comment by nyngwang** [comment]
@RRethy 
Here are some issues which will probably shrink your possible users:

1. For some colorschemes, turn `'termguicolors'` on will make it broken.
2. I have vim, nvim, MacVim on my computer, for me the only case this plugin will work is by adding the line into `.vimrc`, not `.gvimrc`:

```
let g:Hexokinase_highlighters = [ 'sign_column' ]`
```

And the option `virtual` didn't work. (While `backgroundfull`, `sign_column` are correctly rendered.)

My neovim version is (via homebrew):

```
neovim: stable 0.4.4 (bottled)
```

and the following line:

```
let g:Hexokinase_highlighters = [  'virtual', 'sign_column' ]`
```

will cause error message:

```
Error detected while processing function <SNR>69_on_exit_vim[3]..<SNR>69_clear_hl[2]..script /Users/ningwang/.vim/vim-plug-in/vim
-hexokinase/autoload/hexokinase/highlighters/virtual.vim:
line    4:
virtual highlighting only works with Neovim v0.3.2 - please upgrade
Press ENTER or type command to continue
Error detected while processing function <SNR>69_on_exit_vim[3]..<SNR>69_clear_hl:
line    2:
E117: Unknown function: hexokinase#highlighters#virtual#tearDownv2
Error detected while processing function <SNR>69_on_exit_vim:
line    6:
E117: Unknown function: hexokinase#highlighters#virtual#highlightv2
Press ENTER or type command to continue
```

**Comment by RRethy** [comment]
1. That is the colorscheme's problem not a problem with vim-hexokinase, almost all modern terminals support `'termguicolors'`.
2. `virtual` is only for Neovim, Vim doesn't support virtual text. That error you got is because the function `nvim_create_namespace()` is not found in the provided standard library which means you are either using a very old version of Neovim or you are using Vim which doesn't support namespaces (another reason why virtual text won't work). Neovim v0.4.4 does support it, but that error would not show if you were using that version of Neovim.
