### ISSUE TITLE
Support specifying g:Hexokinase_executable_path beforehand

### ISSUE THREAD

**Issue by nogweii** [RRethy/vim-hexokinase#81]
I have my dotfiles copied to a bunch of servers and computers, but not all of them have go installed to be able compile the binary. Using the [AUR package](https://aur.archlinux.org/packages/hexokinase-git/) I can pre-compile and install the program on those servers. This puts the binary at `/usr/bin/hexokinase` rather than in a subdirectory of the plugin, within the submodule.

If I could specify `g:Hexokinase_executable_path` in my configuration, then this sorta odd scenario can be supported. Hopefully, without too much burden.

**Comment by RRethy** [comment]
Mb I thought it was already something that could be overridden but I never set that up, you can use `let g:Hexokinase_executable_path='/usr/bin/hexokinase'` now.

**Comment by nogweii** [comment]
That was quick, it works! Thanks ❤️
