### ISSUE TITLE
Highlighter setting not applied

### ISSUE THREAD

**Issue by Avimitin** [RRethy/vim-hexokinase#86]
I've set the global variable `Hexokinase_highlighters` to `backgroundfull`, but the color still appears like a virtual text.

-  My configuration

```lua
-- I am using packer as my plugin manager

    use {
        'RRethy/vim-hexokinase',
        run = 'make hexokinase',
        cmd = {"HexokinaseToggle"},
        config = function()
            vim.g.Hexokinase_highlighters = {'backgroundfull'}
            vim.g.Hexokinase_optInPatterns = {
                'full_hex', 'rgb', 'rgba', 'hsl', 'hsla'
            }
        end
    }
```

I've tried to inspect the value of the `Hexokinase_highlighters` variable, but I've got the expected value:

```vimscript
:echo g:Hexokinase_highlighters
```

![image](https://user-images.githubusercontent.com/30021675/132992805-5ff91ed7-72e1-4328-9a49-1d71e6b8bc6e.png)

But it showed like below:

![image](https://user-images.githubusercontent.com/30021675/132992837-5833a0f5-b452-4f88-ba0c-623016f86133.png)

My full setting: https://github.com/Avimitin/nvim

**Comment by RRethy** [comment]
What is output of `echo g:Hexokinase_highlightCallbacks`? You might also want to try removed `cmd = {"HexokinaseToggle"}`, autoloading the plugin yourself is usually a bad idea even though packer encourages its use.

**Comment by Avimitin** [comment]
```
:echo g:Hexokinase_highlightCallbacks

[function('hexokinase#highlighters#virtual#highlightv2')]
```

Is this a packer error? The plugin is loaded before config applied?

**Comment by RRethy** [comment]
I don't know how packer works as I don't use it. Did you try removing the lazy loading via `cmd`? As I said, typically manually lazy loading plugins is a bad idea.

**Comment by Avimitin** [comment]
> I don't know how packer works as I don't use it. Did you try removing the lazy loading via `cmd`? As I said, typically manually lazy loading plugins is a bad idea.

Yes, after removing the lazyload setting, the plugin works as expected. So maybe I should open a issue at packer repo to see how to fix it.

**Comment by RRethy** [comment]
Yup, sounds good. Lazy loading the plugin isn't going to do much anyways since if you look at the source code not much is being done at startup. Packer is probably loading the plugin and configuration out of order.
