### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ghost** [RRethy/vim-hexokinase#87]
**Problem:** 

![image](https://user-images.githubusercontent.com/85305219/139557725-a3965e17-0a17-443f-a964-535b585f78e2.png)

**So:**
Is there any possibility that comments that include hex will not be detected?

**Comment by RRethy** [comment]
No, this plugin is not syntax aware and will never be this way. `documentColor` from an LSP could do this but Neovim doesn't support that LSP method currently.
