### ISSUE TITLE
How to enable Hexokinase for all file types?

### ISSUE THREAD

**Issue by CT-66** [RRethy/vim-hexokinase#88]
I would like to turn hexokinase on for all file types by default instead of manually typing `:HexokinaseTurnOn`. I tried adding `:HexokinaseTurnOn` in my init.vim, but I get an error. I tried `let g:Hexokinase_ftEnabled=['*']` but it doesn't work. 

Any ideas on how to make it work? 
Thanks!

**Comment by RRethy** [comment]
By default it is on for all filetypes, you don't need any special configuration. `let g:Hexokinase_ftEnabled=['*']` will actually disable it for all filetypes because `*` is not a filetype.

**Comment by CT-66** [comment]
Thanks a lot.
