### ISSUE TITLE
let hexokinase work in windows

### ISSUE THREAD

**Issue by pangchol** [RRethy/vim-hexokinase#92]
When I try hexokinase in win11 like this:
1. install golang in win11 for build hexokinase
2. install MinGW in win11 and change default "mingw32-make.exe" to "make.exe " for get make comand work
3. open cmd and go hexokinase plug root  dir && run "make hexokinase"
4. success build out hexokinase.exe in hexokinase dir
5. try open css file which include color define.
6. get error :  "未定义的变量: id"

Think about in hexokinase dir has "hexokinase"(for linux) and "hexokinase.exe"(for windows) may confusion to the system. so I change like this:
1. change "hexokinase/hexokinase.exe" file name to "hexokinase/hexokinase_win.exe"
2. change plugin/hexokinase.vim for
`
   let g:Hexokinase_executable_path = get(g:, 'Hexokinase_executable_path',
        \ executable(expand('<sfile>:h:h').'/hexokinase/hexokinase')
        \   ? expand('<sfile>:h:h').'/hexokinase/hexokinase'
        \   : expand($GOPATH).'/bin/hexokinase')
`

to 

`
if has('win32') || has('win32unix')
    let g:Hexokinase_executable_path = get(g:, 'Hexokinase_executable_path',
        \ executable(expand('<sfile>:h:h').'/hexokinase/hexokinase_win')
        \   ? expand('<sfile>:h:h').'/hexokinase/hexokinase_win'
        \   : expand($GOPATH).'/bin/hexokinase_win')
else
    let g:Hexokinase_executable_path = get(g:, 'Hexokinase_executable_path',
        \ executable(expand('<sfile>:h:h').'/hexokinase/hexokinase')
        \   ? expand('<sfile>:h:h').'/hexokinase/hexokinase'
        \   : expand($GOPATH).'/bin/hexokinase')
endif
`
3. test open css file again, and it work fine!

so for support work in windows, just solve the name conflict in "hexokinase\hexokinase" and "hexokinase\hexokinase.exe"

suggest fix this officail.

**Comment by RRethy** [comment]
You can override `g:Hexokinase_executable_path` in your own personal `init.vim`.
