### ISSUE TITLE
can't enable non default highlighters 

### ISSUE THREAD

**Issue by ns740** [RRethy/vim-hexokinase#94]
### Problem
`:let g:Hexokinase_highlighters=['foregroundfull']` 
(or any of the other non-default highlighters) doesn't change the colour display behaviour.   

for me this doesn't seem to depend on OS, terminal app, vim/neovim, ssh/local so I must have something consistently wrong in my setup or be doing something stupid but I can't find what it is.   

### Context
can reproduce on both Linux and MacOS, with both Vim and nvim,  both in and out of tmux and using Alacritty, ITerm2 and Blink (IOS) terminal emulators

installed version of vim-hexokinase plugin for this example was `62324b4 - Sat Apr 24 20:55:19 2021 -0400`

#### MacOS env
- MacOS: 12.4
- Vim: 8.2 (macports HUGE w/o gui) 
- nvim 0.7.0 (Release brew)
- iTerm2 3.4.15
- Alacritty 0.10.1
- tmux 3.2a
#### Linux env
- Linux: Ubuntu 20.04.4LTS
- Vim 8.1 patches thru 3741
- nvim v0.8.0-dev Build:RelWithDebInfo
- Blink: v14.0.10.444 (v14 App Store) via ssh
- tmux 3.0a

environments correctly support 24bit color (tested via `pastel checkcolors` (`pastel` in brew; Ubuntu as a snap) in or out of tmux.

### Reproduce the problem
(this is for vim in macos using iTerm2 outside tmux but others work the same except some tweaks will be required to enable 24bit color in other situation combinations)
using this minimal .vimrc (attached as `vimrc.txt`):
```
call plug#begin('~/.config/nvim/plug.vim')
Plug 'junegunn/vim-plug'
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
call plug#end()
set termguicolors
```
and the test file `hexokinaseTest` (attached as `hexokinaseTest.txt`)
```
vim hexokinaseTest
# it displays like this as expected (the default for vim is g:HexokinaseHighlighers=['sign_column'])
```
<img src="https://user-images.githubusercontent.com/46407531/169956464-dc3820cb-7493-4b5d-aaed-e35c5001f263.png" width=25% height=25%>

```
# now the vim command
:let g:Hexokinase_highlighters=['foregroundfull']
```
doesn't change the display at all (still in the sign column) - it looks like this:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/46407531/169967669-4f99b19f-248d-4570-8b21-377c51f42d37.png">

```
:let g:Hexokinase_highlighters=['backgroundfull']
```
also doesn't change anything.  (same for the other non-default highlighters)

behaviour in nvim is the same except the "locked in" highlighter is 'virtual' (the default for nvim) instead of 'sign_column' so
it looks like this instead
<img width="177" alt="image" src="https://user-images.githubusercontent.com/46407531/169973071-e3690c4c-4aa4-4e94-b82b-d19a613d1ceb.png">
regardless of how i set `g:Hexokinase_highlighters`

### Other information
on the chance that it is something messed up in my setup, here are all the vim variables that seem to be related (this is after entering the `:let g:Hexokinase_highlighters=['foregroundfull']` command in vim).  attached as `hexokinasesettings.txt`
```
Hexokinase_ftOptInPatterns {}
Hexokinase_optOutPatterns
Hexokinase_ftDisabled []
plugs                 {'vim-hexokinase': {'uri': 'https://git::@github.com/rrethy/vim-hexokinase.git', 'dir': '/Users/ns/.config/nvim/plug.vim/vim-hexokinase/', 'frozen': 0, 'branch': '', 'do': 'make hexokinase'}, 'vim-plug': {'uri': 'https://git::@github.com/junegunn/vim-plug.git', 'dir': '/Users/ns/.config/nvim/plug.vim/vim-plug/', 'frozen': 0, 'branch': ''}}
Hexokinase_ftOptOutPatterns {}
Hexokinase_optInPatterns  full_hex,rgb,rgba,hsl,hsla,colour_names
Hexokinase_tearDownCallbacks [function('hexokinase#highlighters#sign_column#tearDownv2')]
Hexokinase_builtinHighlighters ['virtual', 'sign_column', 'background', 'backgroundfull', 'foreground', 'foregroundfull']
Hexokinase_highlighters ['foregroundfull']
Hexokinase_virtualText  ■
Hexokinase_executable_path  /Users/ns/.config/nvim/plug.vim/vim-hexokinase/hexokinase/hexokinase
Hexokinase_v2         #1
Hexokinase_signIcon    ■
Hexokinase_palettes   []
Hexokinase_termDisabled #0
Hexokinase_highlightCallbacks [function('hexokinase#highlighters#sign_column#highlightv2')]
loaded_hexokinase     #1
plugs_order           ['vim-plug', 'vim-hexokinase']
Hexokinase_refreshEvents ['TextChanged', 'InsertLeave', 'BufRead']
b:hexokinase_colours  [{'lnum': '13', 'hlname': 'v2hexokinaseHighlight008000', 'end': '9', 'hex': '#008000', 'start': '5'}, {'lnum': '13', 'hlname': 'v2hexokinaseHighlightff0000', 'end': '3', 'hex': '#ff0000', 'start': '1'}, {'lnum': '12', 'hlname': 'v2hexokinaseHighlight400000', 'end': '20', 'hex': '#400000', 'start': '10'}, {'lnum': '12', 'hlname': 'v2hexokinaseHighlightffff00', 'end': '6', 'hex': '#ffff00', 'start': '1'}, {'lnum': '11', 'hlname': 'v2hexokinaseHighlight220011', 'end': '7', 'hex': '#220011', 'start': '1'}, {'lnum': '10', 'hlname': 'v2hexokinaseHighlight8f0900', 'end': '7', 'hex': '#8f0900', 'start': '1'}, {'lnum': '9', 'hlname': 'v2hexokinaseHighlight400000', 'end': '11', 'hex': '#400000', 'start': '1'}, {'lnum': '8', 'hlname': 'v2hexokinaseHighlight004000', 'end': '11', 'hex': '#004000', 'start': '1'}, {'lnum': '7', 'hlname': 'v2hexokinaseHighlightff0011', 'end': '7', 'hex': '#ff0011', 'start': '1'}, {'lnum': '6', 'hlname': 'v2hexokinaseHighlightffc0cb', 'end': '4', 'hex': '#ffc0cb', 'start': '1'}, {'lnum': '5', 'hlname': 'v2hexokinaseHighlightffff00', 'end': '6', 'hex': '#ffff00', 'start': '1'}, {'lnum': '4', 'hlname': 'v2hexokinaseHighlight0000ff', 'end': '4', 'hex': '#0000ff', 'start': '1'}, {'lnum': '3', 'hlname': 'v2hexokinaseHighlight008000', 'end': '5', 'hex': '#008000', 'start': '1'}, {'lnum': '2', 'hlname': 'v2hexokinaseHighlightffa500', 'end': '6', 'hex': '#ffa500', 'start': '1'}]
b:hexokinase_is_on    #1
b:hexokinase_job       process 66601 dead
b:hexokinase_is_disabled #0
```
i hope this won't be too embarassing but suspect it will be

thanks for your help

[hexokinaseTest.txt](https://github.com/RRethy/vim-hexokinase/files/8759971/hexokinaseTest.txt)
[vimrc.txt](https://github.com/RRethy/vim-hexokinase/files/8759974/vimrc.txt)
[hexokinasesettings.txt](https://github.com/RRethy/vim-hexokinase/files/8760135/hexokinasesettings.txt)

**Comment by RRethy** [comment]
You have to set `g:Hexokinase_highlighters` in your configuration file, e.g.

```vim
call plug#begin('~/.config/nvim/plug.vim')
Plug 'junegunn/vim-plug'
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
call plug#end()
set termguicolors
let g:Hexokinase_highlighters=['backgroundfull']
```

**Comment by ns740** [comment]
> You have to set `g:Hexokinase_highlighters` in your configuration file, e.g.

arrgh :-) embarrassed (as predicted)
thanks
(it's a very fast scrape.   and the nvim highlighter default is probably the best highlighter anyway)
